name: Label community PRs
on:
  pull_request_target:
    types: [opened]
permissions:
  issues: write
  pull-requests: write
jobs:
  add_milestone:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'dotnet/roslyn-analyzers' && github.event.pull_request.author_association != 'MEMBER' && github.event.pull_request.author_association != 'OWNER' }}
    steps:
    - name: Get label data
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ORGANIZATION: dotnet
        REPOSITORY: roslyn-analyzers
        LABEL_NAME: Community
      run: |
        gh api graphql -f query='
          query($org: String!, $repo: String!, $label: String!) {
            repository(name: $repo, owner: $org) {
              label(name: $label) {
                id
              }
            }
          }' -f org=$ORGANIZATION -f repo=$REPOSITORY -f label="$LABEL_NAME" > label_data.json

        echo 'LABEL_ID='$(jq -r '.data.repository.label.id' label_data.json) >> $GITHUB_ENV

    - name: Assign label
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_ID: ${{ github.event.pull_request.node_id }}
      if: ${{ env.LABEL_ID != '' && env.LABEL_ID != 'null' }}
      run: |
        gh api graphql -f query='
          mutation($pull: ID!, $label: ID!) {
            addLabelsToLabelable(input: {labelableId: $pull, labelIds: [$label]}) {
              clientMutationId
            }
          }' -f pull=$PULL_REQUEST_ID -f label=$LABEL_ID
